### ISSUE TITLE
React Native 0.40 conversion?

### ISSUE THREAD

**Issue by aksonov** [transistorsoft/react-native-background-geolocation#185]
All iOS components must use different 'import' paths for React, any plans to release new version for RN 0.40?

**Comment by christocracy** [comment]
I haven't yet tried 0.40.  I'll upgrade my demo app next week and see what's up.

**Comment by christocracy** [comment]
I've been working on this today.  I've got [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch) working with `0.40.0` (required by `background-geolocation`.

**Comment by aksonov** [comment]
Thanks!  I've got 'yoga/Yoga.h not found' compilation error after react-native-background-fetch CocoaPods install, does it mean that RN0.40 doesn't work with CocoaPods?

**Comment by christocracy** [comment]
Upgrade for `0.40.0` is released to `2.4.0`.

@aksonov Show me your `Podfile`

**Comment by aksonov** [comment]
```
platform :ios, '8.0'
use_frameworks!

target 'tinyrobot' do
    pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
    pod 'React', :path => '../node_modules/react-native'
    pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
end
```

**Comment by christocracy** [comment]
Comment out use_frameworks

**Comment by aksonov** [comment]
Tried. Then xmpp will not work

Pavel.

**Comment by christocracy** [comment]
You will have problems using Cocoapods.

Pods don't allow per-pod use_frameworks.
-- 
Snet form Gmail Mobile

**Comment by aksonov** [comment]
So I'm very confused - to use your library and xmpp together I have to use cocoa pods with use frameworks option.

Pavel.

**Comment by christocracy** [comment]
My plugin requires you **not** `use_frameworks!`.

This [this issue](https://github.com/transistorsoft/react-native-background-geolocation/issues/174#issuecomment-262649988)

**Comment by aksonov** [comment]
But I can't use iOS xmpp without this option

**Comment by christocracy** [comment]
The original issue of `0.40.0` conversion is complete.  Open a new issue.
