### ISSUE TITLE
react-native headless task

### ISSUE THREAD

**Issue by atifaziz1** [transistorsoft/react-native-background-geolocation#435]
I am getting this error "No task registered for key BackgroundGeolocation". Please guide me how to solve this issue?

**Comment by christocracy** [comment]
Tell me the steps you have performed in your desire to enable “Headless” mode.

**Comment by atifaziz1** [comment]
This error has been removed now, I am getting this error now
undefined is not a function (evaluating '_reactNativeBackgroundGeolocation2.default.registerHeadlessTask(HeadlessTask)')

I am performing following task
1. registering default.registerHeadlessTask in index.js
2. configure into App.js

and getting error from index.js

**Comment by christocracy** [comment]
If you didn't **ignore the issue template**, I'd be able to tell you.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by rigbot01** [comment]
I am also facing the same issue

**Your Environment**
Plugin version: 2.8.1
Platform: Android
OS version: 0.6
Device manufacturer / model: Emulator
React Native version (react-native -v): 0.35
Plugin config

**Expected Behavior**
Even when app is terminated get location information to the server.

**Actual Behavior**
I am getting the same error as 
undefined is not a function (evaluating '_reactNativeBackgroundGeolocation2.default.registerHeadlessTask(HeadlessTask)')

**Steps to Reproduce**
I have followed the headlessJs steps as specified
1. enableHeadless :true
2. In index.js (App.js)  file registered javascript headless task

**Context**
Send location notification to server even when app is terminated.

**Debug logs**
N/A

**Comment by christocracy** [comment]
Show me adb logcat logs.

**Comment by rigbot01** [comment]
![screenshot_1521462607](https://user-images.githubusercontent.com/28520248/37595677-a9052d9c-2b9f-11e8-89e2-d589a157e683.png)

**Comment by christocracy** [comment]
That is not an $ adb logcat log.

I need to see the Android logs

**Comment by christocracy** [comment]
@atifaziz1 You've ignored the issue template.  I need more information:



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by rigbot01** [comment]
03-20 05:15:58.713  3352  3352 I TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy] 
03-20 05:15:58.713  3352  3352 I TSLocationManager: ╔═════════════════════════════════════════════
03-20 05:15:58.713  3352  3352 I TSLocationManager: ║ MainActivity was destroyed
03-20 05:15:58.713  3352  3352 I TSLocationManager: ╠═════════════════════════════════════════════
03-20 05:15:58.713  3352  3352 I TSLocationManager: ╟─ stopOnTerminate: false
03-20 05:15:58.713  3352  3352 I TSLocationManager: ╟─ enabled: true
03-20 05:15:58.732  3352  3352 I TSLocationManager: [c.t.l.l.TSLocationManager stopWatchPosition] 
03-20 05:15:58.732  3352  3352 I TSLocationManager:   🔴  watchPosition: OFF
03-20 05:15:58.740  1320  1631 W audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
03-20 05:15:58.751  3352  3352 D TSLocationManager: [c.t.l.a.BackgroundGeolocation h] 
03-20 05:15:58.751  3352  3352 D TSLocationManager:   🔴  Cleared callbacks
03-20 05:15:58.765  3352  3352 I TSLocationManager: [c.t.l.a.BackgroundGeolocation removeActivityUpdates] 
03-20 05:15:58.765  3352  3352 I TSLocationManager:   🔴  Stop activity updates
03-20 05:15:58.785  3352  3352 D TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityDestroyed] 
03-20 05:15:58.785  3352  3352 D TSLocationManager: ╔═════════════════════════════════════════════
03-20 05:15:58.785  3352  3352 D TSLocationManager: ║ BackgroundGeolocationService Rx ActivityDestroyed
03-20 05:15:58.785  3352  3352 D TSLocationManager: ╠═════════════════════════════════════════════
03-20 05:15:58.803  3352  3352 I TSLocationManager: [c.t.l.BackgroundGeolocationService i] 
03-20 05:15:58.803  3352  3352 I TSLocationManager:   🔴  Stop heartbeat

**Comment by christocracy** [comment]
@rigbot01 Now show me logs of your app booting.

**Comment by christocracy** [comment]
@rigbot01 And what **version** of the plugin are you using?

**Comment by rigbot01** [comment]
I am using plugin 2.8.1
![screenshot_1521547518](https://user-images.githubusercontent.com/28520248/37653492-1d89d7f6-2c65-11e8-8678-d11e2484862d.png)

**Comment by christocracy** [comment]
Well, that's your problem.  Headless support didn't come until [2.11.0](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#2110---2018-02-03).

The docs you see in master correspond to the **latest version**.

**Comment by atifaziz1** [comment]
@christocracy I am using

Platform: Android
OS version: lollipop
Device manufacturer / model: Motorola / moto g1
React Native version (react-native -v): 0.50.4

**Comment by christocracy** [comment]
@atifaziz1 What **VERSION** of the plugin??

**Comment by atifaziz1** [comment]
@christocracy sir how to check plugin version?

**Comment by christocracy** [comment]
Check your `package.json`

**Comment by atifaziz1** [comment]
@christocracy its 2.10.1

**Comment by christocracy** [comment]
@atifaziz1 Did you [see this comment above](https://github.com/transistorsoft/react-native-background-geolocation/issues/435#issuecomment-374576721)

**Comment by rigbot01** [comment]
Hai now I use plugin 2.12.0-beta.1 but still I get the same issue.
This is the  logcat logs
03-22 05:06:35.202  3336  3336 I TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy] 
03-22 05:06:35.202  3336  3336 I TSLocationManager: ╔═════════════════════════════════════════════
03-22 05:06:35.202  3336  3336 I TSLocationManager: ║ MainActivity was destroyed
03-22 05:06:35.202  3336  3336 I TSLocationManager: ╠═════════════════════════════════════════════
03-22 05:06:35.202  3336  3336 I TSLocationManager: ╟─ stopOnTerminate: true
03-22 05:06:35.202  3336  3336 I TSLocationManager: ╟─ enabled: false
03-22 05:06:35.212  3336  3336 I TSLocationManager: [c.t.l.l.TSLocationManager stopWatchPosition] 
03-22 05:06:35.212  3336  3336 I TSLocationManager:   🔴  watchPosition: OFF
03-22 05:06:35.230  3336  3336 D TSLocationManager: [c.t.l.a.BackgroundGeolocation h] 
03-22 05:06:35.230  3336  3336 D TSLocationManager:   🔴  Cleared callbacks
03-22 05:06:35.251  3336  3336 I TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO close] 
03-22 05:06:35.251  3336  3336 I TSLocationManager:   ✅  Closed database
03-22 05:06:35.269  3336  3336 I TSLocationManager: [c.t.l.l.TSLocationManager stopWatchPosition] 
03-22 05:06:35.269  3336  3336 I TSLocationManager:   🔴  watchPosition: OFF

**Comment by atifaziz1** [comment]
@christocracy yes I have seen you comment.
But sir in demo project same version working fine , problem occurs in my actual project.It's not registering. 
1 question more to you , I don't want push notification on background task. how to disable just push notifications in background task?

**Comment by christocracy** [comment]
@atifaziz1 *Of course* the demo project works, it's using version [`2.11.0`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/package.json#L18)

If you're using `2.10.1`, there **IS NO HEADLESS**.  Upgrade to latest version.

**Comment by christocracy** [comment]
@rigbot01 Show me the config `{}` you're providing the plugin.

**Comment by atifaziz1** [comment]
@christocracy I am using same version in demo project 2.10.1.
Anyhow let me try to update version.

**Comment by christocracy** [comment]
The [CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#2110---2018-02-03) clearly states that "Headless Mode" appear in `2.11.0`

## [2.11.0] - 2018-02-03
- [Added] New Android "Headless" mechanism allowing you provide a simple custom Java class to receive all events from the plugin when your app is terminated (with `stopOnTerminate: false`).  The headless mechanism is enabled with new `@config {Boolean} enableHeadless`.  See the Wiki "Headless Mode" for details.

If you're using *any* version *less than* `2.11.0`, there is **NO** "Headless Mode"

**Comment by rigbot01** [comment]
When I install 2.11.0 and try to build my build fails it gives the following error:

 What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.google.android.gms:play-services-location:11.6.0.
     Searched in the following locations:
         file:/Users/priyankaprakash/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
         file:/Users/priyankaprakash/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/priyankaprakash/Rigbot/RigbotMobile/android/sdk-manager/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/priyankaprakash/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
         file:/Users/priyankaprakash/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/priyankaprakash/Rigbot/RigbotMobile/android/sdk-manager/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
     Required by:
         project :app > project :react-native-background-geolocation

**Comment by christocracy** [comment]
You're probably missing the google maven url in your `android/build.gradle`

```diff
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        // Google now hosts their latest API dependencies on their own maven  server.  
        // React Native will eventually add this to their app template.
+       maven {
+           url 'https://maven.google.com'
+       }
    }
}

**Comment by rigbot01** [comment]
Thanks I had missed that but now too build fails

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :react-native-background-geolocation.

**Comment by christocracy** [comment]
If you’re following the setup steps, those correspond to version 2.12.0, not 2.11.0

**Comment by rigbot01** [comment]
Yah but I didn't follow the ones for 2.12.0

**Comment by christocracy** [comment]
Post your settings.gradle and android/app/build.gradle

**Comment by rigbot01** [comment]
settings.gradle

rootProject.name = 'RigbotMobile'

include ':app'
include ':react-native-prompt-android'
project(':react-native-prompt-android').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-prompt-android/android')
include ':react-native-pdf-view'
project(':react-native-pdf-view').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-pdf-view/android')
include ':react-native-print'
project(':react-native-print').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-print/android')
include ':react-native-html-to-pdf'
project(':react-native-html-to-pdf').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-html-to-pdf/android')
include ':react-native-fs'
project(':react-native-fs').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fs/android')
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android')
include ':react-native-background-timer'
project(':react-native-background-timer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-timer/android')
include ':react-native-usbserial'
project(':react-native-usbserial').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-usbserial/android')
include ':react-native-signature-capture'
project(':react-native-signature-capture').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-signature-capture/android')
include ':react-native-svg'
project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
include ':react-native-background-geolocation'
project(':react-native-background-geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-background-geolocation/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
include ':react-native-fabric'
project(':react-native-fabric').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fabric/android')
include ':react-native-bluetooth-serial'
project(':react-native-bluetooth-serial').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-bluetooth-serial/android')
include ':react-native-share'
project(':react-native-share').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-share/android')


build.gradle

android {
    compileSdkVersion 23
    buildToolsVersion '25.0.0'

    defaultConfig {
        applicationId "com.advayasolutions.rigbot"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 29
        versionName "0.4.2"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    signingConfigs {
        release {
            /*storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD*/
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

// per react-native-background-geolocation install instructions:
repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
}

apply plugin: 'io.fabric'

repositories {
  maven { url 'https://maven.fabric.io/public' }
}
repositories {
  maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
dependencies {
    compile project(':react-native-prompt-android')
    compile project(':react-native-pdf-view')
    compile project(':react-native-print')
    compile project(':react-native-html-to-pdf')
    compile project(':react-native-fs')
    compile project(':react-native-maps')
    compile project(':react-native-background-timer')
    compile project(':react-native-usbserial')
    compile project(':react-native-signature-capture')
    compile project(':react-native-svg')
    compile project(':react-native-device-info')
    compile project(':react-native-background-geolocation')
    compile project(':react-native-vector-icons')
    compile project(':react-native-code-push')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    // per react-native-background-geolocation install instructions:
    compile(name: 'tslocationmanager', ext: 'aar')
    compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }
    compile project(':react-native-fabric')
    compile project(':react-native-bluetooth-serial')
    compile 'com.android.support:multidex:1.0.0'
    compile project(':react-native-share')

// react-native-maps
    compile(project(':react-native-maps')){
         exclude group: 'com.google.android.gms', module: 'play-services-base'
         exclude group: 'com.google.android.gms', module: 'play-services-maps'
     }
     // see https://github.com/airbnb/react-native-maps/pull/877 :
     compile 'com.google.android.gms:play-services-base:+'
     compile 'com.google.android.gms:play-services-maps:+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}

**Comment by christocracy** [comment]
I suggest you install 2.12.0.  Follow the setup instructions carefully as setup has changed.

**Comment by rigbot01** [comment]
OK i shall try that thanks

**Comment by christocracy** [comment]
Take special note of the new Gradle Properties.  Many other modules are now aware of these (including latest react-native-maps) and will align their dependencies to your property values.

I suggest you use compileSdk 26 (not 23 as you currently have).

Be sure to align app-compat-v7 using the supportLibVersion property.

**Comment by rigbot01** [comment]
Thanks, I did follow the steps as specified and still I get this error when I run the build

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find :tslocationmanager:.
     Required by:
         project :app
   > Could not find :tsbackgroundfetch:.
     Required by:
         project :app > project :react-native-background-fetch

**Comment by christocracy** [comment]
Show me your:
- android/build.gradle
- android/app/build.gradle

**Comment by rigbot01** [comment]
android/build.gradle

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
           url 'https://maven.google.com'
       }
       maven {
           url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
       }
       maven {
           url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
       }
    }

    // fix issue affecting all react-native < 0.42.3 as of May 27, 2017
    configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
                    details.useVersion "0.35.0"
                }
            }
        }
    }
}

ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 26
    buildToolsVersion   = "26.0.2"
    supportLibVersion   = "26.1.0"
    googlePlayServicesVersion = "11.8.0"
}


android/app/build.gradle

android {
     compileSdkVersion rootProject.compileSdkVersion
     buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        applicationId "com.advayasolutions.rigbot"
        minSdkVersion 16
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 29
        versionName "0.4.2"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    signingConfigs {
        release {
            /*storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD*/
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

// per react-native-background-geolocation install instructions:
repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
}

apply plugin: 'io.fabric'

repositories {
  maven { url 'https://maven.fabric.io/public' }
}
repositories {
  maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
dependencies {
    compile project(':react-native-background-fetch')
    compile project(':react-native-prompt-android')
    compile project(':react-native-pdf-view')
    compile project(':react-native-print')
    compile project(':react-native-html-to-pdf')
    compile project(':react-native-fs')
    compile project(':react-native-maps')
    compile project(':react-native-background-timer')
    compile project(':react-native-usbserial')
    compile project(':react-native-signature-capture')
    compile project(':react-native-svg')
    compile project(':react-native-device-info')
    compile project(':react-native-background-geolocation')
    compile project(':react-native-vector-icons')
    compile project(':react-native-code-push')
    compile fileTree(dir: "libs", include: ["*.jar"])
  
    compile "com.facebook.react:react-native:+"  // From node_modules
    // per react-native-background-geolocation install instructions:
    compile(name: 'tslocationmanager', ext: 'aar')
    compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }
    compile project(':react-native-fabric')
    compile project(':react-native-bluetooth-serial')
    compile 'com.android.support:multidex:1.0.0'
    compile project(':react-native-share')
    compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
// react-native-maps
    compile(project(':react-native-maps')){
         exclude group: 'com.google.android.gms', module: 'play-services-base'
         exclude group: 'com.google.android.gms', module: 'play-services-maps'
     }
     // see https://github.com/airbnb/react-native-maps/pull/877 :
     compile 'com.google.android.gms:play-services-base:+'
     compile 'com.google.android.gms:play-services-maps:+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}

**Comment by christocracy** [comment]
**Review the setup doc**.  Follow is *exactly*.  You no longer need this:

```
compile(name: 'tslocationmanager', ext: 'aar')
```

Do **not** use `:+` for play-services version — use the new gradle property `googlePlayServicesVersion`

**Comment by rigbot01** [comment]
Thanks but still I am getting the same error.

I have removed 
     compile(name: 'tslocationmanager', ext: 'aar')

and also added
     compile 'com.google.android.gms:play-services-base:$rootProject.googlePlayServicesVersion'


but when I run build I get 

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find :tsbackgroundfetch:.
     Required by:
         project :app > project :react-native-background-fetch

**Comment by christocracy** [comment]
When I say ["**Review the setup doc**](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md#open_file_folder-androidbuildgradle).  Follow *exactly*", I *really* mean that.

That means pay **SPECIAL ATTENTION** to those green bits.
![](https://dl.dropboxusercontent.com/s/yeaubd4g5nf1h69/Screenshot%202018-04-02%2008.03.13.png?dl=1)

**Comment by christocracy** [comment]
And btw, use double-quotes when interpolating variables
```
compile "com.google.android.gms:play-services-base:$rootProject.googlePlayServicesVersion"
```

**Comment by rigbot01** [comment]
Thanks, but i already have those added.

**Comment by christocracy** [comment]
```
npm install --save react-native-background-fetch
```

**Comment by rigbot01** [comment]
Now I get this while running build

/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:13: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskConfig;
                                 ^
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:14: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskContext;
                                 ^
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:15: error: package com.facebook.react.jstasks does not exist
import com.facebook.react.jstasks.HeadlessJsTaskEventListener;
                                 ^
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:22: error: cannot find symbol
public class HeadlessTask implements HeadlessJsTaskEventListener {
                                     ^
  symbol: class HeadlessJsTaskEventListener
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:26: error: cannot find symbol
    private HeadlessJsTaskContext mActiveTaskContext;
            ^
  symbol:   class HeadlessJsTaskContext
  location: class HeadlessTask
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:62: error: cannot find symbol
    protected void startTask(final HeadlessJsTaskConfig taskConfig) {
                                   ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:88: error: cannot find symbol
    private void invokeStartTask(ReactContext reactContext, final HeadlessJsTaskConfig taskConfig) {
                                                                  ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:36: error: cannot find symbol
        HeadlessJsTaskConfig config = new HeadlessJsTaskConfig(HEADLESS_TASK_NAME, new WritableNativeMap(), 30000);
        ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:36: error: cannot find symbol
        HeadlessJsTaskConfig config = new HeadlessJsTaskConfig(HEADLESS_TASK_NAME, new WritableNativeMap(), 30000);
                                          ^
  symbol:   class HeadlessJsTaskConfig
  location: class HeadlessTask
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:45: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:89: error: cannot find symbol
        final HeadlessJsTaskContext headlessJsTaskContext = HeadlessJsTaskContext.getInstance(reactContext);
              ^
  symbol:   class HeadlessJsTaskContext
  location: class HeadlessTask
/Users/priyankaprakash/Rigbot/RigbotMobile/node_modules/react-native-background-fetch/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java:89: error: cannot find symbol
        final HeadlessJsTaskContext headlessJsTaskContext = HeadlessJsTaskContext.getInstance(reactContext);
                                                            ^
  symbol:   variable HeadlessJsTaskContext
  location: class HeadlessTask
13 errors
:react-native-background-fetch:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-fetch:compileReleaseJavaWithJavac'.

**Comment by christocracy** [comment]
>React Native version (react-native -v): 0.35

[0.35.0](https://github.com/facebook/react-native/releases/tag/v0.35.0) dates back to Oct 2016.  It's 2018 now and current react-native version is [0.54.0](https://github.com/facebook/react-native/releases).  Time to upgrade.

**Comment by rigbot01** [comment]
OK thanks, but won't it work with RN 0.35?

**Comment by christocracy** [comment]
As you can see in your logs, no.  Upgrade.

**Comment by rigbot01** [comment]
Ok thanks
