### ISSUE TITLE
npm install not working with v4.0.0

### ISSUE THREAD

**Issue by Tiagojdferreira** [transistorsoft/react-native-background-geolocation#21]
I just tried installing the plugin and at first I got:
````
module.js:338
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:18:11
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
````
By changing to node version v0.12.7 the installation worked, so I assume there is a problem when installing this package with node v4.0.0

**Comment by christocracy** [comment]
I'm using `4.2.1` here.

**Comment by twelvearrays** [comment]
I'm using 4.0.0 here. 



Matt
