### ISSUE TITLE
RNBackgroundGeolocation.addEventListener is not a function

### ISSUE THREAD

**Issue by jpauldan** [transistorsoft/react-native-background-geolocation#1474]
## Your Environment
* Plugin version: 4.6.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Pixel 3A
* React Native version: 0.62.0
* Plugin config (error happens before config so this probably doesn't matter...)
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      // GENERAL OPTIONS
      reset: true,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      foregroundService: true,
      backgroundPermissionRationale: {
        title: "...",
        message: "...",
        positiveAction: "Change to \"Allow all the time\"",
        negativeAction: "Cancel"
      },

      // GEOLOCATION OPTIONS
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      stopAfterElapsedMinutes: 120,
      startOnBoot: false,
      stopOnTerminate: false,
      disableElasticity: true,
      stopDetectionDelay: 15,
      stopTimeout: 15,
      disableStopDetection: true,
      pausesLocationUpdatesAutomatically: false,
      distanceFilter: useAggressiveTracking ? 0 : 3,
      locationUpdateInterval: useAggressiveTracking ? 0 : 1000,
      fastestLocationUpdateInterval: useAggressiveTracking ? 0 : 1000,
      showsBackgroundLocationIndicator: true,

      // HTTP & SQLITE OPTIONS
      url: Config.appConfig.TRACKING_URL + "/api/point",
      httpRootProperty: ".",
      locationTemplate: '{' +
        '"latitude":<%= latitude %>,' +
        '"longitude":<%= longitude %>,' +
        '"timestamp":"<%= timestamp %>",' +
        '"isMoving":"<%= is_moving %>",' +
        '"speed":<%= speed %>,' +
        '"accuracy":<%= accuracy %>,' +
        '"event":"<%= event %>",' +
        '"activity":"<%= activity.type %>",' +
        '"altitude":"<%= altitude %>",' +
        '"heading":"<%= heading %>",' +
        '"odometer":"<%= odometer %>"' +
        '}',
      params: {
        platform: DeviceInfo.getSystemName() + ' ' + DeviceInfo.getSystemVersion(),
        model: DeviceInfo.getModel() + ' (' + DeviceInfo.getDeviceId() + ')',
        brand: DeviceInfo.getBrand(),
        appVersion: DeviceInfo.getVersion()
      },
      batchSync: false,
      autoSync: true,
      maxDaysToPersist: 7,
      headers: {
        "Content-Type": "application/json"
      }
```

## Expected Behavior
listeners can be added.

## Actual Behavior
app fails to load with error: `RNBackgroudnGeolocation.addEventListener is not a function`

## Context
i am upgrading from 3.1.0 to 4.6.0 and followed all the steps. given that we had 3.1.0 working in RN 0.62.0 there didn't seem to be much to update. the auto-linking steps had already been done. i upgraded `buildscript / ext` fields in build.gradle as instructed but i don't see how that would prevent the plugin file from loading properly.

if i remove the `.onLocation` call and keep the `.ready` call after i get no errors. digging into the `BackgroundGeolocation` exported class there appears to be no `addEventListener` function but there is an `addListener` function.

## Debug logs
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
05-05 15:25:02.868 17897 18713 D TSLocationManager: [c.t.l.a.BackgroundGeolocation a]
05-05 15:25:02.868 17897 18713 D TSLocationManager:   ≡ƒö┤  Cleared callbacks
```

</details>

## Relevant Files
<details><summary>android/build.gradle</summary>

```javascript

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        googlePlayServicesLocationVersion = "19.0.1"
        buildToolsVersion = "31.0.0"
        minSdkVersion = 16
        compileSdkVersion = 31
        targetSdkVersion = 31
        appCompatVersion = "1.1.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            // react-native-background-geolocation
            url("${project(':react-native-background-geolocation').projectDir}/libs")
        }
        maven {
            // react-native-background-fetch
            url("${project(':react-native-background-fetch').projectDir}/libs")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

</details>

<details><summary>android/app/build.gradle</summary>

```javascript
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

Project background_geolocation = project(':react-native-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

def jscFlavor = 'org.webkit:android-jsc:+'

def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "XXXXXXXXXXXXXX"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 35
        versionName "4.4.2"
        resValue "string", "build_config_package", "XXXXXXXXXXXXXXXXX"
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('XXXXXXXXXXX')) {
                storeFile file(XXXXXXXXXXXXXXX)
                storePassword XXXXXXXXXXXXXXXX
                keyAlias XXXXXXXXXXXXXXXXXXX
                keyPassword YYYYYYYYYYYYGOTCHA
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            applicationIdSuffix ".debug"
            resValue "string", "app_name", "DEVNAME"
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            resValue "string", "app_name", "RELNAME"
        }
    }

    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    // custom change needed to prevent production build crash on launch - JMB
    implementation'com.facebook.soloader:soloader:0.9.0'

    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'

        // custom change to handle okhttp/flipper/react-native lib conflict - JMB
        // https://github.com/facebook/react-native/issues/28481
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```

</details>

<details><summary>MainApplication.java</summary>

```java
package com.booya.android.supbro;

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
import com.reactnativecommunity.webview.RNCWebViewPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;

import android.content.pm.ApplicationInfo;
import android.os.Build;
import android.webkit.WebView;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      if (0 != (getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE))
      { WebView.setWebContentsDebuggingEnabled(true); }
    }
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.packtrackapp.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```
</details>

**Comment by christocracy** [comment]
I think you’ll fix this if you upgrade RN

**Comment by christocracy** [comment]
The [example app currently uses 66.3](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/d87b7503b042d1716345acdb500ad06ffb5290a6/package.json#L18)

**Comment by christocracy** [comment]
react-native@0.62.0 is [over two years old](https://github.com/facebook/react-native/releases/tag/v0.62.0)

**Comment by christocracy** [comment]
There was some significant refactoring of the plugin event-subscription code due to changes in recent versions of RN.

the plug-in’s event-listeners now return a `Subscription` instance, allowing one to more easily remove single listeners. See the api docs for an example.

**Comment by jpauldan** [comment]
is there somewhere that lists the general dependencies? also i just downgraded to 4.4.6 which works in RN 0.62. 

we considered upgrading RN but it's such an incredible hassle.

**Comment by christocracy** [comment]
There’s nothing in 4.6.0 vs 4.4.6 that would cause your error.

> but it's such an incredible hassle.

You’re using a two year old version of RN, significantly pre-dating both iOS 15 and Android 12.

it’s only going to get harder the longer you wait.  At some point in the near future, you are going to be forced to upgrade.

**Comment by jpauldan** [comment]
i tried going back to 4.6.0 and now it seems to be working. 🤷 
RN in general is pretty finnicky and often fails to build once and then works the second time. overall i'm not too satisfied with it but here we are.

at any rate thanks to who knows what this is a non-issue.

**Comment by christocracy** [comment]
>RNBackgroudnGeolocation.addEventListener is not a function

This method `addEventListener` was removed 6 months ago in `4.4.0`

>i tried going back to 4.6.0 and now it seems to be working

Stale javascript build.

**Comment by mikehardy** [comment]
@jpauldan you'll like https://react-native-community.github.io/upgrade-helper/ - it makes upgrading pretty easy in my opinion, especially if pursued just one major version at a time (e.g., 0.62 to 0.63 first, then to 64 etc). The only difficult transitions in my opinion were 0.59 to 0.60 (autolinking was a big deal...) and now 0.68 to 0.69 as they introduce new architecture. I'm still on 0.68 in my production apps because of that.

With regard to build instability, you may like `npx react-native-clean-project` for reproducible builds, then if you have build flakiness you with caching back in use (after clean project...) that can be isolated and fixed. I do not have problems with reproducible builds in the general case but it does happen sometimes, so for those cases, and when I do release builds, part of my release build process uses react-native-clean-project to make sure I'm truly starting from a known good state. Anything that uses gradle (has caching), Xcode (has caching), cocoapods (has caching) will have these sorts of problems - stated differently - Flutter has these issues as well, it's just an artifact of maintaining state in build systems
